format = '$all'
# format = """ 
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $fill\
# $nodejs\
# $bun\
# $deno\
# $lua\
# $python\
# $ruby\
# $rust\
# $go\
# $zig\
# $c\
# $nix_shell\
# $jobs\
# $time\
# $line_break\
# $character
# """

[fill]
symbol = ' '

[time]
disabled = false

# [rust]
# format = '[$symbol($version )]($style)'

# [nix_shell]
# format = '[$symbol]($style)'

[bun]
symbol = ' '
style = 'bold white'
